const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 899,
      countInStock: 10,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      description: "High quality cotton shirt",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 799,
      countInStock: 10,
      brand: "Puma",
      rating: 4.0,
      numReviews: 20,
      description: "High quality linen shirt",
    },

    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 1099,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "High quality cotton pant",
    },
    {
      name: "Adidas Slim pant",
      slug: "adidas-slim-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 999,
      countInStock: 5,
      brand: "Puma",
      rating: 4.6,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};

export default data;
